-- Migration: add GUIDE role and phone to users
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'GUIDE';
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT true;
