## ─────────────────────────────────────────────────────────────────────────────
## secrets.yaml
##
## ⚠  NUNCA commitear este archivo con valores reales al repositorio.
##    Usá una herramienta como Sealed Secrets, External Secrets Operator
##    o SOPS para gestionar secretos en producción.
##
## Para generar los valores en base64:
##   echo -n "mi_valor" | base64
## ─────────────────────────────────────────────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: viaja-con-moni
  labels:
    app.kubernetes.io/part-of: viaja-con-moni
type: Opaque
data:
  # echo -n "moni" | base64
  POSTGRES_USER:     bW9uaQ==
  # echo -n "supersecret_cambia_esto" | base64
  POSTGRES_PASSWORD: c3VwZXJzZWNyZXRfY2FtYmlhX2VzdG8=
  # echo -n "viajaconmoni" | base64
  POSTGRES_DB:       dmlhamFjb25tb25p

---

apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: viaja-con-moni
  labels:
    app.kubernetes.io/part-of: viaja-con-moni
type: Opaque
data:
  # postgresql://moni:supersecret_cambia_esto@postgres-service:5432/viajaconmoni?schema=public
  # echo -n "postgresql://..." | base64
  DATABASE_URL: cG9zdGdyZXNxbDovL21vbmk6c3VwZXJzZWNyZXRfY2FtYmlhX2VzdG9AcG9zdGdyZXMtc2VydmljZTo1NDMyL3ZpYWphY29ubW9uaT9zY2hlbWE9cHVibGlj

  # echo -n "tu_nextauth_secret_muy_largo_y_aleatorio" | base64
  NEXTAUTH_SECRET: dHVfbmV4dGF1dGhfc2VjcmV0X211eV9sYXJnb195X2FsZWF0b3Jpbw==
